# Generated by Django 4.2.11 on 2024-04-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.CheckConstraint(check=models.Q(('is_root', True), ('parent__isnull', False), _negated=True), name='root_folder_cannot_have_parent'),
        ),
    ]
