# Generated by Django 4.2.11 on 2024-04-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_sharedfolder_sharedfolder_unique_shared_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedFolder',
        ),
    ]
