# Generated by Django 4.2.11 on 2024-04-08 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0004_delete_sharedfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_folders', to=settings.AUTH_USER_MODEL),
        ),
    ]
