# Generated by Django 4.2.11 on 2024-04-08 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0005_folder_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
        # migrations.AddConstraint(
        #     model_name='folder',
        #     constraint=models.CheckConstraint(check=models.Q(('user', models.F('shared_with')), _negated=True), name='cannot_share_with_self'),
        # ),
    ]
